# Generated by Django 5.2.15 on 2026-06-27 13:47

import django.db.models.deletion
import pretix.base.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0001_squashed_0028_auto_20160816_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=190)),
                ('font_file', models.FileField(upload_to='furbadge/fonts/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furbadge_fonts', to='pretixbase.event')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name='BadgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=190)),
                ('background_pdf', models.FileField(upload_to='furbadge/backgrounds/')),
                ('foreground_pdf', models.FileField(null=True, upload_to='furbadge/foregrounds/')),
                ('font_size_max', models.DecimalField(decimal_places=2, default=48.0, max_digits=5)),
                ('font_color', models.CharField(default='#000000', max_length=9)),
                ('text_justify', models.CharField(default='center', max_length=10)),
                ('image_pos_x', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('image_pos_y', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('image_width', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('image_height', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('text_pos_x', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('text_pos_y', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('text_max_width', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('text_max_height', models.DecimalField(decimal_places=2, default=20.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furbadge_types', to='pretixbase.event')),
                ('font', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pretix_furbadge.eventfont')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name='ProductBadgeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('badge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretix_furbadge.badgetype')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furbadge_links', to='pretixbase.event')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furbadge_links', to='pretixbase.item')),
            ],
            options={
                'unique_together': {('event', 'item')},
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name='BadgeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(null=True, upload_to='furbadge/avatars/')),
                ('badge_text', models.CharField(max_length=32)),
                ('telegram_username', models.CharField(max_length=64)),
                ('show_in_public_list', models.BooleanField(default=False)),
                ('show_telegram_in_public_list', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='furbadge_data', to='pretixbase.orderposition')),
                ('badge_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pretix_furbadge.productbadgelink')),
            ],
        ),
    ]
