# Generated by Django 5.2.15 on 2026-07-04 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_furbadge', '0004_baddata_telegram_delivery_mode'),
        ('pretixbase', '0302_alter_customer_locale_alter_user_locale'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='telegramidentity',
            name='unique_telegram_identity_per_organizer',
        ),
        migrations.RemoveField(
            model_name='telegramidentity',
            name='organizer',
        ),
        migrations.AddField(
            model_name='telegramidentity',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_identities', to='pretixbase.event'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='telegramidentity',
            constraint=models.UniqueConstraint(fields=('event', 'telegram_user_id'), name='unique_telegram_identity_per_event'),
        ),
    ]
