# Generated by Django 5.2.15 on 2026-07-04 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_furbadge', '0005_remove_telegramidentity_unique_telegram_identity_per_organizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbadgelink',
            name='badge_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pretix_furbadge.badgetype'),
        ),
    ]
