# Generated by Django 5.2.15 on 2026-07-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_furbadge", "0006_alter_productbadgelink_badge_type"),
        ("pretixbase", "0301_reusablemedium_remove_orderposition"),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramorderlink',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='pretixbase.event'),
            preserve_default=False,
        ),
    ]
