# Generated by Django 5.2.15 on 2026-07-04 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_furbadge', '0007_telegramorderlink_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgedata',
            name='show_telegram_in_public_list',
        ),
        migrations.RemoveField(
            model_name='badgedata',
            name='telegram_delivery_mode',
        ),
        migrations.RemoveField(
            model_name='badgedata',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='telegramorderlink',
            name='public_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramorderlink',
            name='telegram_delivery_mode',
            field=models.CharField(default='email_only', max_length=18),
        ),
        migrations.AlterField(
            model_name='badgedata',
            name='badge_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pretix_furbadge.productbadgelink'),
        ),
        migrations.AlterField(
            model_name='productbadgelink',
            name='badge_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pretix_furbadge.badgetype'),
        ),
    ]
