# Generated by Django 5.2.15 on 2026-07-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_furbadge', '0008_remove_badgedata_show_telegram_in_public_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramorderlink',
            name='telegram_delivery_mode',
            field=models.CharField(default='email_and_telegram', max_length=18),
        ),
    ]
